export const LAY_DANH_SACH_PHIM_ACTION = 'LAY_DANH_SACH_PHIM_ACTION';
export const LAY_CHI_TIET_PHIM_ACTION = 'LAY_CHI_TIET_PHIM_ACTION';
export const THONG_TIN_PHONG_VE_ACTION = 'THONG_TIN_PHONG_VE_ACTION';